# Generated by Django 4.2.19 on 2025-03-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='regno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
